dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: <account>.us-east-1
      user: <login>
      password: <password>
      role: ACCOUNTADMIN
      database: ENEM_STORAGE
      warehouse: COMPUTE_WH
      schema: DATA
